+JobFlavour = "espresso"

periodic_release =  (NumJobStarts < 4) && ((CurrentTime - EnteredCurrentStatus) > 60) 

# need to update executable
getenv     = True 

myPath     = /afs/cern.ch/user/y/ykao/work/esAlignment/CMSSW_8_0_8/src/AlignmentTool/ESAlignTool/test
executable = $(myPath)/condor/script.sh
input      = $(myPath)/AlignIter_cfg.py

should_transfer_files = YES
transfer_input_files  = $(myPath)/inputFiles_cfi.py, $(myPath)/inputMatrixElements_cfi.py
transfer_output_files = ""

output     = $(myPath)/condor/result/out/hello.$(ClusterID).$(ProcID).out
error      = $(myPath)/condor/result/err/hello.$(ClusterID).$(ProcID).err
log        = $(myPath)/condor/result/log/hello.$(ClusterID).$(ProcID).log

iteration = 9
queue arguments from (
    #AlignIter_cfg.py $(iteration) default AlignmentFile_iter$(iteration).root
    AlignIter_cfg.py $(iteration) batch01 AlignmentFile_iter$(iteration)_output01.root
    AlignIter_cfg.py $(iteration) batch02 AlignmentFile_iter$(iteration)_output02.root
    AlignIter_cfg.py $(iteration) batch03 AlignmentFile_iter$(iteration)_output03.root
    AlignIter_cfg.py $(iteration) batch04 AlignmentFile_iter$(iteration)_output04.root
    AlignIter_cfg.py $(iteration) batch05 AlignmentFile_iter$(iteration)_output05.root
)
